### ISSUE TITLE
SCAN+rVV10

### ISSUE THREAD

**Issue by caperott** [maxhutch/quantum-espresso#2]
Hi,
I am giving a try to SCAN+rVV10 using the master branch of QE available at https://github.com/QEF/q-e as of Sept. 24, 2017. QE was compiled against libxc (trunk, > 3.0.0) and rVV10 kernel table was generated by generate_rVV10_kernel_table.x and copied to the pseudo dir. As a test case I chose hexagonal boron nitride. 

The issue I am facing with is that pw.x returns the same energies for input_dft = 'scan' and for input_dft = "scan+sla+pw+rw86+pbc+vv10" (i.e., for SCAN + rVV10). The code seems to identify correctly the string given to input_dft, e.g., for input_dft = 'scan' the output file gives "Exchange-correlation      = SCAN ( 0  0  0  0 0 5)" and, for input_dft = "scan+sla+pw+rw86+pbc+vv10", the output files gives "Exchange-correlation      = SCAN+SLA+PW+RW86+PBC+VV10 ( 1  4 13  4 3 5)". In both cases, however, I got exactly the same energies after SCF convergence,

     one-electron contribution =     -24.10068669 Ry
     hartree contribution      =      19.84906654 Ry
     xc contribution           =      -0.85528009 Ry
     ewald contribution        =     -32.41964182 Ry

Using the same input file with (only) rVV10 worked like a charm, giving the correct interplanar distance for hexagonal boron nitride. Furthermore, when running pw.x with input_dft = 'rVV10' (or "sla+pw+rw86+pbc+vv10") I got the following in the output file:

---------------------------------------------------------------------------------
Carrying out rVV10 run using the following parameters:
Nqs =      20    Nr_points =    1024   r_max =   100.000
b_value =  6.30000    beta =  0.00901
     q_mesh =  0.00010000  0.00030000  0.00058939  0.00100810
               0.00161396  0.00249058  0.00375900  0.00559430
               0.00824984  0.01209221  0.01765183  0.02569619
               0.03733578  0.05417739  0.07854596  0.11380545
               0.16482331  0.23864234  0.34545298  0.50000000

Gradients computed in Reciprocal space

---------------------------------------------------------------------------------
The above message does not appears in the output file when using  input_dft =  "scan+sla+pw+rw86+pbc+vv10".

It seems that rVV10 is not being used in calculations with input_dft =  "scan+sla+pw+rw86+pbc+vv10"...

Here is the input file I used in these tests:

&CONTROL
title = 'hBN'
calculation = 'scf'
restart_mode = 'from_scratch'
outdir = './files'
wfcdir = './files'
pseudo_dir = "../pseudo"
prefix = 'hbn'
disk_io = 'default'
verbosity = 'default'
nstep = 400
/

&SYSTEM
space_group = 194
a = 2.503374
c = 6.80
origin_choice = 1
nat = 2
ntyp = 2
ecutwfc = 120
ecutrho = 480
input_dft = "scan+sla+pw+rw86+pbc+vv10"
/

&ELECTRONS
electron_maxstep = 200
conv_thr = 1.0D-9
diago_thr_init = 1e-4
startingpot = 'atomic'
startingwfc = 'atomic'
mixing_mode = 'plain'
mixing_beta = 0.5
mixing_ndim = 8
diagonalization = 'david'
/

ATOMIC_SPECIES
B   10.8110000000  B.pbe-hgh.UPF
N   14.0067000000  N.pbe-hgh.UPF

ATOMIC_POSITIONS crystal_sg
B      0.33333333333333       0.66666666666667       0.25000000000000
N      0.33333333333333       0.66666666666667       0.75000000000000

K_POINTS automatic
21  21  7   0 0 0

Regards,
Claudio

**Comment by pchuy1906** [comment]
Hi Claudio,
I have the same problem. How can you solve this problem?
Thanks,
Huy

**Comment by caperott** [comment]
Huy,

Unfortunately, I did not solve the problem. In fact, despite SCAN_rVV10 is
available from libxc, the non-local correlation is not computed by
libxc and, accordingly, using  SCAN_rVV10 withing QE is not just a matter
of including the libxc funcs_id associated to this xc functional.

Sorry...

Claudio


-- 

Cláudio A. Perottoni

Universidade de Caxias do Sul
Rua Francisco Getúlio Vargas, 1130
95070-560 Caxias do Sul - RS - Brazil
http://www.researcherid.com/rid/B-8409-2008

**Comment by pchuy1906** [comment]
I see. Thank you!
Huy
